"""Extend WorkInstruction created_by to VARCHAR 5000

Revision ID: 39087d8d45d2
Revises: a88673f40c4b
Create Date: 2025-09-30 17:28:52.248454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39087d8d45d2'
down_revision = 'a88673f40c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_admins', schema=None) as batch_op:
        batch_op.alter_column('login_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('login_is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.create_unique_constraint(None, ['login_username'])

    with op.batch_alter_table('work_instruction', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_instruction', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('login_admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('login_is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('login_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
