"""Add formula and unit fields to QuoteSubItem

Revision ID: 81b86374c14f
Revises: bdf85402f9f9
Create Date: 2025-07-17 09:25:54.876233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b86374c14f'
down_revision = 'bdf85402f9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_sub_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formula', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_sub_item', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('formula')

    # ### end Alembic commands ###
