"""Add Invoice model for billing system

Revision ID: a7891be14f84
Revises: 0ccda95a8a5c
Create Date: 2025-07-20 20:57:11.340884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7891be14f84'
down_revision = '0ccda95a8a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vat_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('gross_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('payment_terms', sa.Integer(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('project_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_description', sa.TEXT(), nullable=True))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('payment_terms')
        batch_op.drop_column('gross_amount')
        batch_op.drop_column('vat_amount')
        batch_op.drop_column('vat_rate')

    # ### end Alembic commands ###
