"""Add QuoteSubItem compatible fields to PositionTemplateSubItem

Revision ID: adf23043d567
Revises: e1de36245d94
Create Date: 2025-07-17 18:32:34.885194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf23043d567'
down_revision = 'e1de36245d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position_template_subitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_quantity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('part_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hourly_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.alter_column('supplier',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_constraint(batch_op.f('fk_template_subitem_supplier'), type_='foreignkey')
        batch_op.drop_column('base_price')
        batch_op.drop_column('supplier_id')

    with op.batch_alter_table('quote_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_quote_item_supplier'), type_='foreignkey')
        batch_op.drop_column('calculation_hours')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('calculation_width')
        batch_op.drop_column('formula')
        batch_op.drop_column('calculation_area')
        batch_op.drop_column('part_number')
        batch_op.drop_column('calculation_length')
        batch_op.drop_column('calculation_height')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculation_height', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('calculation_length', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('part_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('calculation_area', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('formula', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('calculation_width', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('calculation_hours', sa.FLOAT(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_quote_item_supplier'), 'supplier', ['supplier_id'], ['id'])

    with op.batch_alter_table('position_template_subitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('base_price', sa.FLOAT(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_template_subitem_supplier'), 'supplier', ['supplier_id'], ['id'])
        batch_op.alter_column('quantity',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('supplier',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('price')
        batch_op.drop_column('unit_price')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('hours')
        batch_op.drop_column('part_price')
        batch_op.drop_column('part_quantity')

    # ### end Alembic commands ###
