"""Add PositionTemplate models

Revision ID: ccde2953ef03
Revises: 
Create Date: 2025-07-15 19:12:31.575569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccde2953ef03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_template_subitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('formula', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['position_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('position_template')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_template',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('sub_position', sa.VARCHAR(length=10), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('requires_order', sa.BOOLEAN(), nullable=True),
    sa.Column('standard_supplier', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('position_template_subitems')
    op.drop_table('position_templates')
    # ### end Alembic commands ###
