"""Add calculation fields and supplier integration

Revision ID: e1de36245d94
Revises: 81b86374c14f
Create Date: 2025-07-17 09:47:45.728648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1de36245d94'
down_revision = '81b86374c14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position_template_subitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('part_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('requires_order', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'supplier', ['supplier_id'], ['id'])

    with op.batch_alter_table('quote_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculation_length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calculation_width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calculation_height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calculation_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calculation_area', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('formula', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('part_number', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'supplier', ['supplier_id'], ['id'])

    with op.batch_alter_table('quote_sub_item', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('formula')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_sub_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formula', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=32), nullable=True))

    with op.batch_alter_table('quote_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('part_number')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('formula')
        batch_op.drop_column('calculation_area')
        batch_op.drop_column('calculation_hours')
        batch_op.drop_column('calculation_height')
        batch_op.drop_column('calculation_width')
        batch_op.drop_column('calculation_length')

    with op.batch_alter_table('position_template_subitems', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('requires_order')
        batch_op.drop_column('part_number')
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
