"""Add price_display_mode to Quote model

Revision ID: f984fcb32ea5
Revises: adf23043d567
Create Date: 2025-07-20 18:58:31.417459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f984fcb32ea5'
down_revision = 'adf23043d567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position_templates', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_display_mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('price_display_mode')

    with op.batch_alter_table('position_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
